/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class chapter_detail_req_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("chapter_detail_req_t");
    private static const CHAPTER_TYPE_FIELD_DESC:TField = new TField("chapter_type", TType.I32, 1);

    private var _chapter_type:int;
    public static const CHAPTER_TYPE:int = 1;

    private var __isset_chapter_type:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[CHAPTER_TYPE] = new FieldMetaData("chapter_type", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
    }
    {
      FieldMetaData.addStructMetaDataMap(chapter_detail_req_t, metaDataMap);
    }

    public function chapter_detail_req_t() {
      this._chapter_type = 0;
    }

    public function get chapter_type():int {
      return this._chapter_type;
    }

    public function set chapter_type(chapter_type:int):void {
      this._chapter_type = chapter_type;
      this.__isset_chapter_type = true;
    }

    public function unsetChapter_type():void {
      this.__isset_chapter_type = false;
    }

    // Returns true if field chapter_type is set (has been assigned a value) and false otherwise
    public function isSetChapter_type():Boolean {
      return this.__isset_chapter_type;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case CHAPTER_TYPE:
        if (value == null) {
          unsetChapter_type();
        } else {
          this.chapter_type = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case CHAPTER_TYPE:
        return this.chapter_type;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case CHAPTER_TYPE:
        return isSetChapter_type();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case CHAPTER_TYPE:
            if (field.type == TType.I32) {
              this.chapter_type = iprot.readI32();
              this.__isset_chapter_type = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CHAPTER_TYPE_FIELD_DESC);
      oprot.writeI32(this.chapter_type);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("chapter_detail_req_t(");
      var first:Boolean = true;

      ret += "chapter_type:";
      ret += this.chapter_type;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
