/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class confirm_add_friend_req_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("confirm_add_friend_req_t");
    private static const UID_FIELD_DESC:TField = new TField("uid", TType.I32, 1);
    private static const PERMIT_FLAG_FIELD_DESC:TField = new TField("permit_flag", TType.BOOL, 2);

    private var _uid:int;
    public static const UID:int = 1;
    private var _permit_flag:Boolean;
    public static const PERMIT_FLAG:int = 2;

    private var __isset_uid:Boolean = false;
    private var __isset_permit_flag:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[UID] = new FieldMetaData("uid", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[PERMIT_FLAG] = new FieldMetaData("permit_flag", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.BOOL));
    }
    {
      FieldMetaData.addStructMetaDataMap(confirm_add_friend_req_t, metaDataMap);
    }

    public function confirm_add_friend_req_t() {
      this._uid = 0;
      this._permit_flag = 0;
    }

    public function get uid():int {
      return this._uid;
    }

    public function set uid(uid:int):void {
      this._uid = uid;
      this.__isset_uid = true;
    }

    public function unsetUid():void {
      this.__isset_uid = false;
    }

    // Returns true if field uid is set (has been assigned a value) and false otherwise
    public function isSetUid():Boolean {
      return this.__isset_uid;
    }

    public function get permit_flag():Boolean {
      return this._permit_flag;
    }

    public function set permit_flag(permit_flag:Boolean):void {
      this._permit_flag = permit_flag;
      this.__isset_permit_flag = true;
    }

    public function unsetPermit_flag():void {
      this.__isset_permit_flag = false;
    }

    // Returns true if field permit_flag is set (has been assigned a value) and false otherwise
    public function isSetPermit_flag():Boolean {
      return this.__isset_permit_flag;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case UID:
        if (value == null) {
          unsetUid();
        } else {
          this.uid = value;
        }
        break;

      case PERMIT_FLAG:
        if (value == null) {
          unsetPermit_flag();
        } else {
          this.permit_flag = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case UID:
        return this.uid;
      case PERMIT_FLAG:
        return this.permit_flag;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case UID:
        return isSetUid();
      case PERMIT_FLAG:
        return isSetPermit_flag();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case UID:
            if (field.type == TType.I32) {
              this.uid = iprot.readI32();
              this.__isset_uid = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case PERMIT_FLAG:
            if (field.type == TType.BOOL) {
              this.permit_flag = iprot.readBool();
              this.__isset_permit_flag = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(UID_FIELD_DESC);
      oprot.writeI32(this.uid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PERMIT_FLAG_FIELD_DESC);
      oprot.writeBool(this.permit_flag);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("confirm_add_friend_req_t(");
      var first:Boolean = true;

      ret += "uid:";
      ret += this.uid;
      first = false;
      if (!first) ret +=  ", ";
      ret += "permit_flag:";
      ret += this.permit_flag;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
