/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class error_code_ret_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("error_code_ret_t");
    private static const ERROR_CODE_FIELD_DESC:TField = new TField("error_code", TType.I32, 1);
    private static const ERROR_MSG_FIELD_DESC:TField = new TField("error_msg", TType.STRING, 2);

    private var _error_code:int;
    public static const ERROR_CODE:int = 1;
    private var _error_msg:String;
    public static const ERROR_MSG:int = 2;

    private var __isset_error_code:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[ERROR_CODE] = new FieldMetaData("error_code", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[ERROR_MSG] = new FieldMetaData("error_msg", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING));
    }
    {
      FieldMetaData.addStructMetaDataMap(error_code_ret_t, metaDataMap);
    }

    public function error_code_ret_t() {
      this._error_code = 0;
    }

    public function get error_code():int {
      return this._error_code;
    }

    public function set error_code(error_code:int):void {
      this._error_code = error_code;
      this.__isset_error_code = true;
    }

    public function unsetError_code():void {
      this.__isset_error_code = false;
    }

    // Returns true if field error_code is set (has been assigned a value) and false otherwise
    public function isSetError_code():Boolean {
      return this.__isset_error_code;
    }

    public function get error_msg():String {
      return this._error_msg;
    }

    public function set error_msg(error_msg:String):void {
      this._error_msg = error_msg;
    }

    public function unsetError_msg():void {
      this.error_msg = null;
    }

    // Returns true if field error_msg is set (has been assigned a value) and false otherwise
    public function isSetError_msg():Boolean {
      return this.error_msg != null;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case ERROR_CODE:
        if (value == null) {
          unsetError_code();
        } else {
          this.error_code = value;
        }
        break;

      case ERROR_MSG:
        if (value == null) {
          unsetError_msg();
        } else {
          this.error_msg = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case ERROR_CODE:
        return this.error_code;
      case ERROR_MSG:
        return this.error_msg;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case ERROR_CODE:
        return isSetError_code();
      case ERROR_MSG:
        return isSetError_msg();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case ERROR_CODE:
            if (field.type == TType.I32) {
              this.error_code = iprot.readI32();
              this.__isset_error_code = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case ERROR_MSG:
            if (field.type == TType.STRING) {
              this.error_msg = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(this.error_code);
      oprot.writeFieldEnd();
      if (this.error_msg != null) {
        oprot.writeFieldBegin(ERROR_MSG_FIELD_DESC);
        oprot.writeString(this.error_msg);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("error_code_ret_t(");
      var first:Boolean = true;

      ret += "error_code:";
      ret += this.error_code;
      first = false;
      if (!first) ret +=  ", ";
      ret += "error_msg:";
      if (this.error_msg == null) {
        ret += "null";
      } else {
        ret += this.error_msg;
      }
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
