/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class friend_info_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("friend_info_t");
    private static const FRIEND_LIST_FIELD_DESC:TField = new TField("friend_list", TType.LIST, 1);

    private var _friend_list:Array;
    public static const FRIEND_LIST:int = 1;


    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[FRIEND_LIST] = new FieldMetaData("friend_list", TFieldRequirementType.DEFAULT, 
          new ListMetaData(TType.LIST, 
              new StructMetaData(TType.STRUCT, friend_t)));
    }
    {
      FieldMetaData.addStructMetaDataMap(friend_info_t, metaDataMap);
    }

    public function friend_info_t() {
    }

    public function get friend_list():Array {
      return this._friend_list;
    }

    public function set friend_list(friend_list:Array):void {
      this._friend_list = friend_list;
    }

    public function unsetFriend_list():void {
      this.friend_list = null;
    }

    // Returns true if field friend_list is set (has been assigned a value) and false otherwise
    public function isSetFriend_list():Boolean {
      return this.friend_list != null;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case FRIEND_LIST:
        if (value == null) {
          unsetFriend_list();
        } else {
          this.friend_list = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case FRIEND_LIST:
        return this.friend_list;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case FRIEND_LIST:
        return isSetFriend_list();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case FRIEND_LIST:
            if (field.type == TType.LIST) {
              {
                var _list55:TList = iprot.readListBegin();
                this.friend_list = new Array();
                for (var _i56:int = 0; _i56 < _list55.size; ++_i56)
                {
                  var _elem57:friend_t;
                  _elem57 = new friend_t();
                  _elem57.read(iprot);
                  this.friend_list.push(_elem57);
                }
                iprot.readListEnd();
              }
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.friend_list != null) {
        oprot.writeFieldBegin(FRIEND_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRUCT, this.friend_list.length));
          for each (var elem58:* in this.friend_list)          {
            elem58.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("friend_info_t(");
      var first:Boolean = true;

      ret += "friend_list:";
      if (this.friend_list == null) {
        ret += "null";
      } else {
        ret += this.friend_list;
      }
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
