/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class item_type_e   {
    public static const ITEM_NONE:int = 0;
    public static const ITEM_TIPS:int = 1;
    public static const ITEM_BROOM:int = 2;
    public static const ITEM_NEXT:int = 3;
    public static const ITEM_TIME:int = 4;
    public static const ITEM_BOMB:int = 5;

    public static const VALID_VALUES:Set = new Set(ITEM_NONE, ITEM_TIPS, ITEM_BROOM, ITEM_NEXT, ITEM_TIME, ITEM_BOMB);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[ITEM_NONE] = "ITEM_NONE";
      VALUES_TO_NAMES[ITEM_TIPS] = "ITEM_TIPS";
      VALUES_TO_NAMES[ITEM_BROOM] = "ITEM_BROOM";
      VALUES_TO_NAMES[ITEM_NEXT] = "ITEM_NEXT";
      VALUES_TO_NAMES[ITEM_TIME] = "ITEM_TIME";
      VALUES_TO_NAMES[ITEM_BOMB] = "ITEM_BOMB";

    }
  }
}
