/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class next_word_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("next_word_t");
    private static const ANSWER_FLAG_FIELD_DESC:TField = new TField("answer_flag", TType.BOOL, 1);
    private static const INC_COIN_FIELD_DESC:TField = new TField("inc_coin", TType.I16, 2);
    private static const UID_FIELD_DESC:TField = new TField("uid", TType.I32, 4);

    private var _answer_flag:Boolean;
    public static const ANSWER_FLAG:int = 1;
    private var _inc_coin:int;
    public static const INC_COIN:int = 2;
    private var _uid:int;
    public static const UID:int = 4;

    private var __isset_answer_flag:Boolean = false;
    private var __isset_inc_coin:Boolean = false;
    private var __isset_uid:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[ANSWER_FLAG] = new FieldMetaData("answer_flag", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.BOOL));
      metaDataMap[INC_COIN] = new FieldMetaData("inc_coin", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I16));
      metaDataMap[UID] = new FieldMetaData("uid", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
    }
    {
      FieldMetaData.addStructMetaDataMap(next_word_t, metaDataMap);
    }

    public function next_word_t() {
      this._answer_flag = 0;
      this._inc_coin = 0;
      this._uid = 0;
    }

    public function get answer_flag():Boolean {
      return this._answer_flag;
    }

    public function set answer_flag(answer_flag:Boolean):void {
      this._answer_flag = answer_flag;
      this.__isset_answer_flag = true;
    }

    public function unsetAnswer_flag():void {
      this.__isset_answer_flag = false;
    }

    // Returns true if field answer_flag is set (has been assigned a value) and false otherwise
    public function isSetAnswer_flag():Boolean {
      return this.__isset_answer_flag;
    }

    public function get inc_coin():int {
      return this._inc_coin;
    }

    public function set inc_coin(inc_coin:int):void {
      this._inc_coin = inc_coin;
      this.__isset_inc_coin = true;
    }

    public function unsetInc_coin():void {
      this.__isset_inc_coin = false;
    }

    // Returns true if field inc_coin is set (has been assigned a value) and false otherwise
    public function isSetInc_coin():Boolean {
      return this.__isset_inc_coin;
    }

    public function get uid():int {
      return this._uid;
    }

    public function set uid(uid:int):void {
      this._uid = uid;
      this.__isset_uid = true;
    }

    public function unsetUid():void {
      this.__isset_uid = false;
    }

    // Returns true if field uid is set (has been assigned a value) and false otherwise
    public function isSetUid():Boolean {
      return this.__isset_uid;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case ANSWER_FLAG:
        if (value == null) {
          unsetAnswer_flag();
        } else {
          this.answer_flag = value;
        }
        break;

      case INC_COIN:
        if (value == null) {
          unsetInc_coin();
        } else {
          this.inc_coin = value;
        }
        break;

      case UID:
        if (value == null) {
          unsetUid();
        } else {
          this.uid = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case ANSWER_FLAG:
        return this.answer_flag;
      case INC_COIN:
        return this.inc_coin;
      case UID:
        return this.uid;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case ANSWER_FLAG:
        return isSetAnswer_flag();
      case INC_COIN:
        return isSetInc_coin();
      case UID:
        return isSetUid();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case ANSWER_FLAG:
            if (field.type == TType.BOOL) {
              this.answer_flag = iprot.readBool();
              this.__isset_answer_flag = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case INC_COIN:
            if (field.type == TType.I16) {
              this.inc_coin = iprot.readI16();
              this.__isset_inc_coin = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case UID:
            if (field.type == TType.I32) {
              this.uid = iprot.readI32();
              this.__isset_uid = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ANSWER_FLAG_FIELD_DESC);
      oprot.writeBool(this.answer_flag);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(INC_COIN_FIELD_DESC);
      oprot.writeI16(this.inc_coin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UID_FIELD_DESC);
      oprot.writeI32(this.uid);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("next_word_t(");
      var first:Boolean = true;

      ret += "answer_flag:";
      ret += this.answer_flag;
      first = false;
      if (!first) ret +=  ", ";
      ret += "inc_coin:";
      ret += this.inc_coin;
      first = false;
      if (!first) ret +=  ", ";
      ret += "uid:";
      ret += this.uid;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
