/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class search_user_ret_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("search_user_ret_t");
    private static const USER_LIST_FIELD_DESC:TField = new TField("user_list", TType.LIST, 1);

    private var _user_list:Array;
    public static const USER_LIST:int = 1;


    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[USER_LIST] = new FieldMetaData("user_list", TFieldRequirementType.DEFAULT, 
          new ListMetaData(TType.LIST, 
              new StructMetaData(TType.STRUCT, user_status_ret_t)));
    }
    {
      FieldMetaData.addStructMetaDataMap(search_user_ret_t, metaDataMap);
    }

    public function search_user_ret_t() {
    }

    public function get user_list():Array {
      return this._user_list;
    }

    public function set user_list(user_list:Array):void {
      this._user_list = user_list;
    }

    public function unsetUser_list():void {
      this.user_list = null;
    }

    // Returns true if field user_list is set (has been assigned a value) and false otherwise
    public function isSetUser_list():Boolean {
      return this.user_list != null;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case USER_LIST:
        if (value == null) {
          unsetUser_list();
        } else {
          this.user_list = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case USER_LIST:
        return this.user_list;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case USER_LIST:
        return isSetUser_list();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case USER_LIST:
            if (field.type == TType.LIST) {
              {
                var _list277:TList = iprot.readListBegin();
                this.user_list = new Array();
                for (var _i278:int = 0; _i278 < _list277.size; ++_i278)
                {
                  var _elem279:user_status_ret_t;
                  _elem279 = new user_status_ret_t();
                  _elem279.read(iprot);
                  this.user_list.push(_elem279);
                }
                iprot.readListEnd();
              }
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.user_list != null) {
        oprot.writeFieldBegin(USER_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRUCT, this.user_list.length));
          for each (var elem280:* in this.user_list)          {
            elem280.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("search_user_ret_t(");
      var first:Boolean = true;

      ret += "user_list:";
      if (this.user_list == null) {
        ret += "null";
      } else {
        ret += this.user_list;
      }
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
