/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class select_item_bubble_req_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("select_item_bubble_req_t");
    private static const BUBBLE_ID_FIELD_DESC:TField = new TField("bubble_id", TType.I16, 1);

    private var _bubble_id:int;
    public static const BUBBLE_ID:int = 1;

    private var __isset_bubble_id:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[BUBBLE_ID] = new FieldMetaData("bubble_id", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I16));
    }
    {
      FieldMetaData.addStructMetaDataMap(select_item_bubble_req_t, metaDataMap);
    }

    public function select_item_bubble_req_t() {
      this._bubble_id = 0;
    }

    public function get bubble_id():int {
      return this._bubble_id;
    }

    public function set bubble_id(bubble_id:int):void {
      this._bubble_id = bubble_id;
      this.__isset_bubble_id = true;
    }

    public function unsetBubble_id():void {
      this.__isset_bubble_id = false;
    }

    // Returns true if field bubble_id is set (has been assigned a value) and false otherwise
    public function isSetBubble_id():Boolean {
      return this.__isset_bubble_id;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case BUBBLE_ID:
        if (value == null) {
          unsetBubble_id();
        } else {
          this.bubble_id = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case BUBBLE_ID:
        return this.bubble_id;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case BUBBLE_ID:
        return isSetBubble_id();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case BUBBLE_ID:
            if (field.type == TType.I16) {
              this.bubble_id = iprot.readI16();
              this.__isset_bubble_id = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BUBBLE_ID_FIELD_DESC);
      oprot.writeI16(this.bubble_id);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("select_item_bubble_req_t(");
      var first:Boolean = true;

      ret += "bubble_id:";
      ret += this.bubble_id;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
