/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class task_accept_award_req_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("task_accept_award_req_t");
    private static const TASK_ID_FIELD_DESC:TField = new TField("task_id", TType.I32, 1);

    private var _task_id:int;
    public static const TASK_ID:int = 1;

    private var __isset_task_id:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[TASK_ID] = new FieldMetaData("task_id", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
    }
    {
      FieldMetaData.addStructMetaDataMap(task_accept_award_req_t, metaDataMap);
    }

    public function task_accept_award_req_t() {
      this._task_id = 0;
    }

    public function get task_id():int {
      return this._task_id;
    }

    public function set task_id(task_id:int):void {
      this._task_id = task_id;
      this.__isset_task_id = true;
    }

    public function unsetTask_id():void {
      this.__isset_task_id = false;
    }

    // Returns true if field task_id is set (has been assigned a value) and false otherwise
    public function isSetTask_id():Boolean {
      return this.__isset_task_id;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case TASK_ID:
        if (value == null) {
          unsetTask_id();
        } else {
          this.task_id = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case TASK_ID:
        return this.task_id;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case TASK_ID:
        return isSetTask_id();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case TASK_ID:
            if (field.type == TType.I32) {
              this.task_id = iprot.readI32();
              this.__isset_task_id = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
      oprot.writeI32(this.task_id);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("task_accept_award_req_t(");
      var first:Boolean = true;

      ret += "task_id:";
      ret += this.task_id;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
