/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class update_property_ret_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("update_property_ret_t");
    private static const EXP_FIELD_DESC:TField = new TField("exp", TType.I32, 1);
    private static const LEVEL_FIELD_DESC:TField = new TField("level", TType.I32, 2);
    private static const COIN_FIELD_DESC:TField = new TField("coin", TType.I32, 3);
    private static const RIGHT_WORDS_NUM_FIELD_DESC:TField = new TField("right_words_num", TType.I32, 4);
    private static const WRONG_WORDS_NUM_FIELD_DESC:TField = new TField("wrong_words_num", TType.I32, 5);

    private var _exp:int;
    public static const EXP:int = 1;
    private var _level:int;
    public static const LEVEL:int = 2;
    private var _coin:int;
    public static const COIN:int = 3;
    private var _right_words_num:int;
    public static const RIGHT_WORDS_NUM:int = 4;
    private var _wrong_words_num:int;
    public static const WRONG_WORDS_NUM:int = 5;

    private var __isset_exp:Boolean = false;
    private var __isset_level:Boolean = false;
    private var __isset_coin:Boolean = false;
    private var __isset_right_words_num:Boolean = false;
    private var __isset_wrong_words_num:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[EXP] = new FieldMetaData("exp", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[LEVEL] = new FieldMetaData("level", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[COIN] = new FieldMetaData("coin", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[RIGHT_WORDS_NUM] = new FieldMetaData("right_words_num", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
      metaDataMap[WRONG_WORDS_NUM] = new FieldMetaData("wrong_words_num", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
    }
    {
      FieldMetaData.addStructMetaDataMap(update_property_ret_t, metaDataMap);
    }

    public function update_property_ret_t() {
      this._exp = 0;
      this._level = 0;
      this._coin = 0;
      this._right_words_num = 0;
      this._wrong_words_num = 0;
    }

    public function get exp():int {
      return this._exp;
    }

    public function set exp(exp:int):void {
      this._exp = exp;
      this.__isset_exp = true;
    }

    public function unsetExp():void {
      this.__isset_exp = false;
    }

    // Returns true if field exp is set (has been assigned a value) and false otherwise
    public function isSetExp():Boolean {
      return this.__isset_exp;
    }

    public function get level():int {
      return this._level;
    }

    public function set level(level:int):void {
      this._level = level;
      this.__isset_level = true;
    }

    public function unsetLevel():void {
      this.__isset_level = false;
    }

    // Returns true if field level is set (has been assigned a value) and false otherwise
    public function isSetLevel():Boolean {
      return this.__isset_level;
    }

    public function get coin():int {
      return this._coin;
    }

    public function set coin(coin:int):void {
      this._coin = coin;
      this.__isset_coin = true;
    }

    public function unsetCoin():void {
      this.__isset_coin = false;
    }

    // Returns true if field coin is set (has been assigned a value) and false otherwise
    public function isSetCoin():Boolean {
      return this.__isset_coin;
    }

    public function get right_words_num():int {
      return this._right_words_num;
    }

    public function set right_words_num(right_words_num:int):void {
      this._right_words_num = right_words_num;
      this.__isset_right_words_num = true;
    }

    public function unsetRight_words_num():void {
      this.__isset_right_words_num = false;
    }

    // Returns true if field right_words_num is set (has been assigned a value) and false otherwise
    public function isSetRight_words_num():Boolean {
      return this.__isset_right_words_num;
    }

    public function get wrong_words_num():int {
      return this._wrong_words_num;
    }

    public function set wrong_words_num(wrong_words_num:int):void {
      this._wrong_words_num = wrong_words_num;
      this.__isset_wrong_words_num = true;
    }

    public function unsetWrong_words_num():void {
      this.__isset_wrong_words_num = false;
    }

    // Returns true if field wrong_words_num is set (has been assigned a value) and false otherwise
    public function isSetWrong_words_num():Boolean {
      return this.__isset_wrong_words_num;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case EXP:
        if (value == null) {
          unsetExp();
        } else {
          this.exp = value;
        }
        break;

      case LEVEL:
        if (value == null) {
          unsetLevel();
        } else {
          this.level = value;
        }
        break;

      case COIN:
        if (value == null) {
          unsetCoin();
        } else {
          this.coin = value;
        }
        break;

      case RIGHT_WORDS_NUM:
        if (value == null) {
          unsetRight_words_num();
        } else {
          this.right_words_num = value;
        }
        break;

      case WRONG_WORDS_NUM:
        if (value == null) {
          unsetWrong_words_num();
        } else {
          this.wrong_words_num = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case EXP:
        return this.exp;
      case LEVEL:
        return this.level;
      case COIN:
        return this.coin;
      case RIGHT_WORDS_NUM:
        return this.right_words_num;
      case WRONG_WORDS_NUM:
        return this.wrong_words_num;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case EXP:
        return isSetExp();
      case LEVEL:
        return isSetLevel();
      case COIN:
        return isSetCoin();
      case RIGHT_WORDS_NUM:
        return isSetRight_words_num();
      case WRONG_WORDS_NUM:
        return isSetWrong_words_num();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case EXP:
            if (field.type == TType.I32) {
              this.exp = iprot.readI32();
              this.__isset_exp = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case LEVEL:
            if (field.type == TType.I32) {
              this.level = iprot.readI32();
              this.__isset_level = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case COIN:
            if (field.type == TType.I32) {
              this.coin = iprot.readI32();
              this.__isset_coin = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case RIGHT_WORDS_NUM:
            if (field.type == TType.I32) {
              this.right_words_num = iprot.readI32();
              this.__isset_right_words_num = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case WRONG_WORDS_NUM:
            if (field.type == TType.I32) {
              this.wrong_words_num = iprot.readI32();
              this.__isset_wrong_words_num = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(EXP_FIELD_DESC);
      oprot.writeI32(this.exp);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LEVEL_FIELD_DESC);
      oprot.writeI32(this.level);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COIN_FIELD_DESC);
      oprot.writeI32(this.coin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RIGHT_WORDS_NUM_FIELD_DESC);
      oprot.writeI32(this.right_words_num);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(WRONG_WORDS_NUM_FIELD_DESC);
      oprot.writeI32(this.wrong_words_num);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("update_property_ret_t(");
      var first:Boolean = true;

      ret += "exp:";
      ret += this.exp;
      first = false;
      if (!first) ret +=  ", ";
      ret += "level:";
      ret += this.level;
      first = false;
      if (!first) ret +=  ", ";
      ret += "coin:";
      ret += this.coin;
      first = false;
      if (!first) ret +=  ", ";
      ret += "right_words_num:";
      ret += this.right_words_num;
      first = false;
      if (!first) ret +=  ", ";
      ret += "wrong_words_num:";
      ret += this.wrong_words_num;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
