/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class world_type_e   {
    public static const LAKE:int = 0;
    public static const DESERT:int = 1;
    public static const FOREST:int = 2;
    public static const VOLCANO:int = 3;
    public static const ISLAND:int = 4;
    public static const SKY:int = 5;

    public static const VALID_VALUES:Set = new Set(LAKE, DESERT, FOREST, VOLCANO, ISLAND, SKY);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[LAKE] = "LAKE";
      VALUES_TO_NAMES[DESERT] = "DESERT";
      VALUES_TO_NAMES[FOREST] = "FOREST";
      VALUES_TO_NAMES[VOLCANO] = "VOLCANO";
      VALUES_TO_NAMES[ISLAND] = "ISLAND";
      VALUES_TO_NAMES[SKY] = "SKY";

    }
  }
}
